### ISSUE TITLE
review code base

### ISSUE THREAD

**Issue by smeierzubiesen** [smeierzubiesen/hmh#3]
- [X] code/win32_handmade.cpp   2 : Add a better comment template for new .cpp and .h files
- [ ] code/win32_handmade.cpp  26 : This message gets called when the window is getting closed.
- [X] code/win32_handmade.cpp  34 : This won't be needed anymore
- [ ] code/win32_handmade.cpp  69 : Check wether HREDRAW and VREDRAW are still necessary
- [ ] code/win32_handmade.cpp  73 : Make an icon and stick it in here.
- [ ] code/win32_handmade.cpp  80 : maybe some versioning here?
- [ ] code/win32_handmade.cpp 105 : Log this event !WindowHandle
- [ ] code/win32_handmade.cpp 110 : Log this event !RegisterClass
- [X] misc/shell.bat 1 : make script more robust for different environments

**Comment by mitoskalandiel** [comment]
this should be closed once we are done with day 5, although some things are still outstanding.

we might want to start with raising issues seperately
